trigger:
- none

pool: 
  vmImage: ubuntu-latest

variables: 
  - template: ../variables.yaml

steps:
# Step 1: Run a PowerShell script to upload the file to S3
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Assuming AWS CLI and AWS Tools for PowerShell are configured on the agent
      $env:AWS_DEFAULT_REGION = "$(awsRegion)"
      
      # Upload file to S3 using AWS PowerShell Module
      Write-Host "Uploading CopyS3andRestore.ps1 to S3..."
      Write-S3Object -BucketName "$(s3BucketName)" -File "$(Build.SourcesDirectory)/ServerDeployment/databases/CopyS3andRestore.ps1" -Key "CopyS3andRestore.ps1"
  displayName: 'Upload File to S3 via PowerShell'