trigger:
- none

pool: 
  vmImage: ubuntu-latest

variables: 
  - template: ../variables.yaml

steps:
- task: S3Upload@1
  inputs:
    awsCredentials: '$(aws)'
    regionName: '(awsRegion)'
    bucketName: '$(s3BucketName)'
    sourceFolder: '$(Build.Repository.LocalPath)/$(sourceDirectory)'
    targetFolder: '/'  # Target folder in the S3 bucket; '/' means the root
    flattenFolders: false  # Set to false if you want to maintain the directory structure
  displayName: 'Upload Files to S3'