trigger:
- none

pool: 
  vmImage: ubuntu-latest

variables: 
  - template: ../variables.yaml

steps:
# Step 1: Use PowerShell to Upload File to S3 via AWS CLI
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo "Uploading CopyS3andRestore.ps1 to S3 using AWS CLI..."
      aws s3 cp "$(Build.SourcesDirectory)/ServerDeployment/databases/CopyS3andRestore.ps1" "s3://$(s3BucketName)/"
  displayName: 'Upload File to S3 via AWS CLI'