trigger:
- none

pool: 
  vmImage: ubuntu-latest

variables: 
  - template: ../variables.yaml

steps:
# Step 1: Configure AWS credentials (if needed)
- task: UseAwsCredentials@1
  inputs:
    awsCredentials: '${{variables.awsCredentials}}'  # Use the AWS service connection
    regionName: '${{variables.awsRegion}}'

# Step 2: List files in the directory (optional, for debugging)
- script: |
    echo "Listing files in the directory:"
    dir $(Build.SourcesDirectory)/ServerDeployment/databases
  displayName: 'List Files in Directory'

# Step 3: Upload specific file to S3 using AWS CLI
- script: |
    echo "Uploading CopyS3andRestore.ps1 to S3"
    aws s3 cp "$(Build.SourcesDirectory)\ServerDeployment\databases\CopyS3andRestore.ps1" "s3://$(variables.s3BucketName)/"
  displayName: 'Upload File to S3 via AWS CLI'