trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  - template: ../variables.yaml

steps:
# Step 1: Create or Update CloudFormation Stack
- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: '$(awsCredentials)'  # Referencing the variable from the included file
    regionName: '$(awsRegion)'
    stackName: '$(stackName)'
    templateFile: '$(Build.SourcesDirectory)/ServerDeployment/AwsAutomatedRestore/wynsure-dev-cf2.yaml'  # Adjust the path if necessary
    capabilities: 'CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND'
  displayName: 'Create or Update CloudFormation Stack'
