trigger:
- none

pool: 
  vmImage: ubuntu-latest

variables: 
  - template: ../variables.yaml

steps:
- checkout: self
  displayName: 'Checkout Repository'

# - task: AWSCLI@1  # Azure DevOps task to run AWS CLI commands
#   inputs:
#     awsCredentials: $(awsCredentials)  # Service connection name
#     regionName: $(awsRegion)  # AWS region
#     awsCommand: 's3'  # The main AWS CLI command
#     awsSubCommand: 'cp $(Build.SourcesDirectory)/ServerDeployment/databases/CopyS3andRestore.ps1 s3://$(S3BucketName)/CopyS3andRestore.ps1'  # The sub-command to execute
#   displayName: 'Upload Files to S3 using AWS CLI'
- task: AWSCLI@1
  inputs:
    awsCredentials: 'aws-deployment-user'
    regionName: 'us-east-1'
    awsCommand: 's3' 
    awsSubCommand: 'cp $(Build.SourcesDirectory)/CopyS3andRestore.ps1 s3://$(s3BucketName)/CopyS3andRestore.ps1'

- script: |
    echo "Listing directory structure for verification"
    ls -R $(Build.SourcesDirectory)
  displayName: 'Print Directory Structure'