trigger:
- none

pool: 
  vmImage: ubuntu-latest

variables: 
  - template: ../variables.yaml

steps:
- checkout: self
  displayName: 'Checkout Repository'

- task: AWSCLI@1  # Azure DevOps task to run AWS CLI commands
  inputs:
    awsCredentials: 'your-aws-service-connection-name'  # Service connection name
    regionName: $(awsRegion)
    command: 's3 cp $(Build.SourcesDirectory)/$(sourceDirectory) s3://$(S3BucketName)/CopyS3andRestore.ps1'
  displayName: 'Upload Files to S3 using AWS CLI'

- script: |
    echo "Listing directory structure for verification"
    ls -R $(Build.SourcesDirectory)
  displayName: 'Print Directory Structure'