trigger:
- none

pool: 
  vmImage: ubuntu-latest

variables: 
  - template: ../variables.yaml

steps:
- checkout: self
  displayName: 'Checkout Repository'

- task: AWSCLI@1  # Azure DevOps task to run AWS CLI commands
  inputs:
    awsCredentials: $(awsCredentials)  # Service connection name
    regionName: $(awsRegion)  # AWS region
    awsCommand: 's3 cp $(Build.SourcesDirectory)/ServerDeployment/databases/CopyS3andRestore.ps1 s3://$(S3BucketName)/CopyS3andRestore.ps1'  # The actual AWS CLI command to run
  displayName: 'Upload Files to S3 using AWS CLI'

- script: |
    echo "Listing directory structure for verification"
    ls -R $(Build.SourcesDirectory)
  displayName: 'Print Directory Structure'