trigger:
- none

pool: 
  vmImage: ubuntu-latest

variables: 
  - template: ../variables.yaml

steps:
- task: S3Upload@1
  inputs:
    awsCredentials: '${{variables.awsCredentials}}'
    regionName: '${{variables.awsRegion}}'
    bucketName: '${{variables.s3BucketName}}'
    sourceFolder: '$(Build.SourcesDirectory)/ServerDeployment/databases/'
    sourceFiles: 'CopyS3andRestore.ps1'
    targetFolder: ''  # Target folder in the S3 bucket; '/' means the root
    flattenFolders: True  # Set to false if you want to maintain the directory structure
  displayName: 'Upload Files to S3'

- script: |
    echo "Removing unwanted files from S3 bucket"
    files_to_delete=$(aws s3 ls s3://${{ variables.s3BucketName }}/ --recursive | awk '{print $4}' | grep -v "CopyS3andRestore.ps1")
    
    echo "Files to delete:"
    echo "$files_to_delete"
    
    if [ -n "$files_to_delete" ]; then
      for file in $files_to_delete; do
        echo "Deleting $file from S3 bucket"
        aws s3 rm s3://${{ variables.s3BucketName }}/$file || echo "Failed to delete $file"
      done
    else
      echo "No unwanted files found."
    fi
  displayName: 'Remove Unwanted Files from S3'